### PR TITLE
Create pull_request.md

### PR DESCRIPTION
**Pull request by Virentanti**
If you want  any more edits to this template please let me know int the comment 😃

### CODE REVIEW

**Review by rohan472000 — COMMENTED** [review]
see this one:
https://github.com/rohan472000/Java-DSA-InterviewPrep/blob/main/.github/pull_request_template.md

**Comment by rohan472000** [comment]
> If you want any more edits to this template please let me know int the comment 😃

here you should explain about your PR description, not comments.

**Comment by Virentanti** [comment]
Alright, gonna make the changes.

**Review by Virentanti — COMMENTED** [review]
@rohan472000 Please review the changes and let me know if any more changes are required.

**Review by rohan472000 — APPROVED** [review]

**Comment by rohan472000** [comment]
Thanks for your contribution.

**Pull request merged**
